# Numpy
### 공식 홈페이지) https://docs.scipy.org/doc/
#### ■파이썬 단점: 속도가 느리다.
    - 계산 관련하여 여러 노력들이 있었음. 
        -(1)★좋은 컴퓨터를 사용합니다. 
            - 요즘은 gpgpu: general 퍼포스 지피우
        -(2)★분산 환경
    - 이런 노력들에는 돈이 많이 들어요. 그렇다면 돈을 안 들이고 어떻게 파이썬의 단점인 속도를 향상시킬 수 있을까?
        -(3)★파이썬은 인터프린터이지만, 이걸 컴파일 할 수 있어요.
        ->> 가장 유명한게 싸이썬. 
            - □ Cython: 자료형을 지정합니다.
                - (파이썬은 자료형 지정 안 함) C와 속도가 유사함. (파이썬은 C보다 5배 정도 속도 느림)
                - 다만 파이썬과 문법이 조금 다름
            - □Pypy: 파이썬으로 만든 파이썬
                - 장점1)다이나믹 타입드, 길 등을 최적화하여 파이썬보다 5배 빠름
                - 장점2)문법 수정할 필요가 없음
                - 단점1)호환성 문제(써드파티메모리)
        -(4)★파이썬이 글루 랭귀지라서 c, java 등으로 만들었기에 다른 언어와 잘 만남. 
            - 따라서 병목이 생기는 곳을 c하고 짜
            - 파이썬은 공식적으로 C하고 붙일 수 있어요.
                
        -(5)★자료구조 알고리즘
            - 계산 관련하여 속도를 빠르게 한 라이브러리가 '넌파이'
                - 보통 파이썬보다 5배~20배 빠름. 

## ■넌파이 쓰는 이유
    -1. 속도가 빠르다.(5~20배)
        - 속도가 왜 빠를까요?
            - C로 만들었음
            - 데이터구조와 알고리즘으로 만들어 졌댔죠.
            - ■ Vectorization
                - 벡터? 고등학교때 행렬 왜 사용했니. 
                    - 한번에 여러개의 수를 계산할 수 있음. 
                    - 현재 cpu는 si 기법으로 벡터를 최적화해서 사용할 수 있음. 
                        - ■CPU? 넌파이는 cpu 지원하나?
                            - 넌파이는 gpu 지원을 안 해요. 그래서 구글에서 텐서를, 토치에서 텐서를 만든거에요. 
                            넌파이를 지원 안하니까 넌파이로 gpu 기능을 추가
                 - 어레이?
                     - 컴퓨터 사이언스쪽 언어가 array, 수학적언어는 vector. 
                     - 여러개를 한번에 표현한다는 의미로 동일함.
                     - 특징1) 얘는 for문을 돌리지 않음. 루프가 없음. 
                         - 이유) 루프를 돌리면 속도가 느려짐
                         - ■루프 안 쓰는것 3가지? //이제 재귀(제가)컴 맵(컴백)
                             - 1.이터레이터, 제네레이터
                             - 2. 컴프리헨션
                             - 3. 재귀함수
                             - 4. 맵 필터 리듀스 하이 아더 (@@)
                             - 함수형 패러다임도 for 별로 안 쓴다고 했죠. 벡터라이제이션도 포 안쓰고 연산을 해요. (연산 효율↓)
                     - 어레이는 굉장히 어려워요. 수학까지 잘 해야해서. 이거 잘한다고 하면 실력 향상엔 도움 되고 우린 이거 多.
                     - □문제1) 항상 빠르지 않음
                         - 숫자가 클수록 빠르지, 숫자가 작으면 어레이 속도가 느릴 수 있어서 무조건 사용하지는 않음
    -2. 편하고 쉽다.
        - 아나콘다 만든 회사 이름이 '컨티넘'이고, 이 회사를 만든 사람이 '넌파이'만든 사람

#### ■넌파이를 학교에서 안 배운 이유?
    - 넌파이는 '로우 레벨'
        - 텐서플로의 구조, 판다스, 파이토치 내부구조등이 넌파이로 만들어졌지만 학교에서는 ; 
    - 넌파이로 하나하나 하면 선형대수, 확통 등 알고리즘을 짜면 실력도 많이 들긴 해요. 

#### 교수님 정리
    - 넌파이 사용하는 이유2개(쉽고 빠르다)
    - 넌파이 왜 빠르냐 (c로 만들어졌고, 데이터구조가 앤디어레이라는 벡터라이즈된 데이터 구조를 사용했기에)(벡터라이즈는 어레이. 여러개를 하나의 묶음으로 처리하는 애인데, 연산을 for 없이 연산한다. 그게 백터라이즈이다. 그래서 현대의 씨피유는 이걸 연산하는것까지 지원해주기에 더 빠르다)
    

# ■ 어레이
- //가로 벡터
    - 1차원벡터:방향O. 
        - 스칼라: 방향 없이 크기 있는것
        - 1차원 벡터: 방향이 있지만 방향이 없다고 생각하는게 좋아요.
     - 2차원 벡터: 메트릭스
     - 3차원: 패널 데이터 (= 텐서)
         - 텐서플로우는 교안(p.9)이용함
         - 'NDArray'라고 합니다. 
         
         
- //세로
     - 일차원 벡터, 이차원 매트릭스, 3차원 텐서, n차원 텐서
     
- 이미지는 몇 차원?/ 동영상은 몇 차원?
    - 2차원/ 3,4차원


- 따라서 '벡터화'시키는게 관건
    - RGB ) 겹치면 3차원
    - RGB 더 겹치면) 4차원.
    - 어떻게 겹칠지는 우리의 역할
    
==============================================================
# Numpy
#### - 사용하는 이유: 빠르고 쉽다. 
    - 다른 빠른 애들은 어렵다. 
    - 파이썬2는 사실 속도가 더 빨랐음. 파이썬3는 유니코드가 기본이고, 파이썬2는 바이트가 기본. 
####  사람들이 파이썬2에서 3로 늦게 넘어간 이유
        - 따라서 처리해야할 애가 더 많으니까 파이썬3는 느렸대. 파이썬3가 2008년도에 나왔을 당시 느렸으나, 파이썬 3,4부터는 동일 속도
        - 넌파이에서 파이썬3를 아주 늦게 시작했음. 
            - 파이썬은 안 쓰는데 넌파이만 쓰는 문법도 있음.

==============================================================

#### 파이썬 공식이 아니라 빌트인이 아니기에 임포트 해야함

In [1]:
import numpy as np

#### dir 해서 보면 수학관련된게 많음.
- 참고로 대문자가 우선적으로 등장함.
    - dir과 __dir의 차이가 정렬문제.
    - 대문자 A는 65, 소문자는 97. 따라서 대문자부터 나옴
    - 관례상으로 파이썬은 상수가 없음. 
    - 파이썬은 명시적인 상수가 없고, 대문자로 다 있으면 상수처럼 쓴다고 했음
 - 넌파이는 하나의 데이터 구조
     - 데이터는 2가지 방법으로 생성할 수 있음. 
         - 1.인스턴스)순수한 객체라서
         - 2.리터럴) 파이썬 고유 타입만 지원. @@@
         - 이제는 하나 더 알아야함 as 디자인 패턴측면. 
         - 3.팩토리 메소드) 인스턴스 하지 않고, 다른 함수의 힘을 빌어서 인스턴스화 하는것
             - 1) np.array

In [3]:
dir(np) 

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

#### array 거슬리는거 없어요>
- 파이썬 공식 라이브러레에서는 
    - import array
- array는 일반적으로 호모지니어스한 데이터 타입이에요
    -1.스트링 3총사
    -2.레인지

#### 호모지니어스 장점?
    - 속도가 빠름. 
         - 다음 데이터 타입이 뭐가 올지 체크할 필요 없음.

In [ ]:
import numpy as np 

In [4]:
a=np.array #최소한 1개 이상 데이터 넣어야함. 근데 order?

# array
- array 타입: 호모 지니어스한 타입. 
- 데이터가 1개 이상인 애
    - 리스트, 튜플
- C하고 포트란 방식으로 데이터 저장.
-

In [6]:
a=np.array(1) #1개

In [7]:
a

array(1)

In [8]:
a=np.array([1,2]) #2개_리스트

In [9]:
a

array([1, 2])

In [10]:
a=np.array((1,2)) #개 튜플- 결과보니까 리스트로 표현함

In [15]:
a #0차원 스칼라에 1차원 벡터

array([1, 2])

#### 튜플넣었는데 리스트로 출력되네. 어레이는 뮤터블/이뮤터블? 뮤터블
- 
- 카피개념 알아야한다.
    - 스왈라카피/딥카피

### 아웃풋에 어레이라고 나오면? 넌파이임★★★★★★★★
- 혹은 뒤에 넌파이라고 표현이 되어요. (텐서플로 공부하면 알거에요)
- 우리 텐서플로 안하고 파이토치로 딥러닝 하기로 했고, 텐서플로는 교수님이 다다음주에 2일만에 끝내신대
- 이번주 목요일에 데이터 진흥원에서 피자사주러온대요.

#### 그렇다면 type은?

In [14]:
type(a) #ndarray라고 나오는걸 보니, 저래요

numpy.ndarray

#### n차원 만들려면

In [16]:
a=np.array([[1,2],[3,4]])

In [17]:
a

array([[1, 2],
       [3, 4]])

#### 3차원?

In [20]:
a=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [22]:
a # 잘 보면 사이에 공백이 있어. 이거 판때기 사이에 공백 있따 생각해. 
# 공백= 데이터가 하나 겹쳐져 있따 @@

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

#### 타입 쳤을때 numpy.ndarray 나왔으면 만들 수 있나
- 클래스. 클래스는 인스턴스 하면된다.

In [23]:
n=np.ndarray(0)

In [24]:
n

array([], dtype=float64)

#### 우리가 객체 이용해서 이렇게 만들 수 있지만 미묘하게 결과가 달라요
- 위의 예시에서 dtype 거슬리죠?
    - 얘는 호모지니어스라고 했음. 호모지니어스인데 왜 데이터 타입이 중요할까 다 똑같지 않나?

#### 만일 호모지니어스하지 않게 바꾸면 어떻게 되나요?

In [26]:
a=np.array(['1',2,3])

In [29]:
a #dtype에 이상한 애가 뜨네요. 갑자기문자열로 싹 다 바뀌었어요

array(['1', '2', '3'], dtype='<U1')

#### 다시 ndarray
- 이 경우는 타입 에러
- 인스턴스 만드는 경우
    1. 클래스로 인스턴스화
    2. 리터럴
        - float는 0.0으로, str은 ""방식으로
    3. 팩토리 메소드 방식
        - 인스턴스를 조금더 쉽고 편리하게 만들려고 매핑하는 방식
        - 그냥 인스턴스했더니 호모지니어스 아니면 에러가 나죠. 근데 팩토리 메소드 썼더니 다른 데이터 형태로 변경
            - 위에서 a=np.array(['1',2,3]) 했더니 다 문자열로 변경하는식

In [30]:
n=np.ndarray([0,'1'])

TypeError: 'str' object cannot be interpreted as an integer

#### dtype <U1
- 넌파이는 로우레벨
- 얘는 C방식 포트란 방식, 리틀앤디언, 빅 앤디언 방식으로 지원
- < 는 리틀 앤디언, >는 빅앤디언

#### 리틀앤디언, 빅앤디언
####  넌파이는 C로 만들어졌음. 따라서 dtype이라는 애가 거의 C를 지원하는 데이터 타입으로 만들 수 있음.
- 우리가 C처럼 int8, 16, 64 이렇게 구분해서 만들 수 있음
- 메모리량 속도 관리할 수 있음. C처럼. 따라서 dtype이 굉장히 중요한 이슈

#### d-type
- 어떤 인스턴스 알기 위해서 쓰는거
    - dir) 쓸 수 있는 어트리뷰트
    - 바즈)인스턴스 변수가 가지는애

In [31]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

#### 바즈해서 타입 에러. __dict가 `ㅡ정의 안 되면 이런 type 에러나

In [33]:
vars(a) #바즈해서 타입 에러. __dict가 정의 안 되면 이런 type 에러나

TypeError: vars() argument must have __dict__ attribute

#### 차원을 아는 방법?
- ndim : 차원
- len : 차원
- shape :몇행 몇열. 연산할때 모양 맞추는게 중요해서 얘도 중요해
- flags: 씨인지 포트란인지
    - 씨는 옆으로, 포트란은 아래로
- size:원소의 갯수
- itemsize: 하나가 몇 비트인가
- dtype

In [51]:
a=np.array([[1,2],[3,4]])

In [52]:
a 

array([[1, 2],
       [3, 4]])

In [53]:
a.ndim #얘는 이차원

2

In [54]:
len(a)

2

In [55]:
a.shape# 몇행 몇렬

(2, 2)

#### flags
- C방식인지 포트란 방식인지 알려줌
- 포트란은 밑으로, 씨는 옆으로

In [45]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [49]:
a.item

<function ndarray.item>

In [48]:
a.itemsize

4

In [50]:
a.dtype #

dtype('int32')

#### 만일 같은게 있다고 해볼게요
- 넌파이구조: 각각 엘리멘트끼리 계산하여 편하게 벡터 연산을 할 수 있음
- 리스트: 뒤에 추가가됨

In [56]:
a=np.array([[1,2],[3,4]])

In [57]:
b=np.array([[1,2],[3,4]])

In [60]:
a+b #벡터 연산

array([[2, 4],
       [6, 8]])

In [58]:
x=[1,2,3,4]
y=[2,3,4,5]
x+y#뒤에 추가됨

[1, 2, 3, 4, 2, 3, 4, 5]

#### 만일 ????????
- 즉 이렇게 안 해도 더하기 연산으로 쉽게 할 수 있대
- 컴프리 핸션 오케이?

In [61]:
[a+b for a,b in zip(a,b)]

[array([2, 4]), array([6, 8])]

#### 빼기

In [64]:
a-b

array([[0, 0],
       [0, 0]])

#### 곱하기

In [65]:
a*b

array([[ 1,  4],
       [ 9, 16]])

## 엘리멘트 와이즈 방식
#### 이렇게 넌파이는 편리하게 수학적 연산을 할 수 있어요
- a*b
- a+b
- a-b

#### 행간 열을 바꾸는 함수
- a.T

In [67]:
a.T

array([[1, 3],
       [2, 4]])

#### NUMPY
- statsmodel
    - R을 베낌

- 사이킷
    - 영상처리할때쓰는 사이킷도 넌파이로 만들었어요

- 사이킷 런
    - 넌파이로 만들었어요
- 판다스
    - 데이터 기초 분석할때 쓸거라 깊게 
- 멧 플랏립
    - 그래프 그릴거고

#### Scipy
- 특히 넌파이 중에서 사람들이 많이 사용하는 함수
- 과학 분야별로 아주 많이 사용되는 함수들로 numpy 기반
- 장점1) 조회해서 사용하면됨. 많이 계산되는거 굳이 구현 안 해도 됨
    - stats) 통계에서 많이 사용하는것, linalags, sparse, signal 등

#### 이제 조금 더 깊게 들어가요
### 왜 넘파이가 빠를까?
- 씨로 만들었고/호모지니어스이고/벡터라이즈
- (추가)넌파이 내부주소
    - 파이썬의 리스트는 '링크드리스트' 형식으로 구현이 되어요. 메모리가 일렬로 저장되지 않고 타입없으니 계속 체크를 해야하여 속도 느림.
    - 넌파이는 데이터를 전부 일련로 다 저장해. 몇 번째 몇번째. 이것만 체크하면 돼. 
    - 넌파이 내부구조는 일련임. 
        - stride [12/4]를 통해 3행3열로 사람에게 보이기는 하나, 실제로는 일열로 저장되는 구조라 빨라요
#### 내부 구조 몇번째 어디인지 어떻게 찾나
        - 맨 앞 header에 dat-type이 적혀있어요. 파이썬은 데이터 타입을 체크하는데, 얘는 체크 안해요. 호모지니어스니까 다 저장되있고
        - 몇 번째 하면 거기로 바로 점프해버리니까 연산 속도가 빠를 수 밖에 없는 구조. 

#### 아이템 사이즈 
- dtype, dim, dimensions, strides[12|4], data
    - stride. 원래 내부구조는 한 열로 저장된ㄴ데 스트라이드 도입하여 12/4 즉 3개씩 잘라서 사람에게는 3행3열짜리로 보이게 해
    - 즉 내부구조는 다 일련이야. 

#### strides
- 최대공약수로 나눠. 2개가 한 행 가져. 

In [72]:
a.strides

(8, 4)

## 교수님 정리
- 빠르고 쉽다
    - 빠르다) c로 만들어졌고, 효율적인 자료구조이다.
        - 효율적인 자료구조: 호모지니어스+일련저장하고 strides로 표현
    - 이게 넌파이가 빠른 이유
- 이제 쉽다로 넘어갈거에요

## NUMPY 쉬운 이유
- 데이터 구조 정하는거 어려워요
- 예) 이미지 처리에서 RGB 색상을 256이니까 2^8승까지 필요하죠. 
    - 근데 만일 파이썬으로 처리한다고 하면 그보다 더 큰 애를 쓸 수 밖에 없어요. 
    - 그럼 속도도 느리고 메모리 효율성도 떨어져
    - 근데 파이썬으로 한정시킬 수 있을까?
        - 있어요. 인터닝 기법을 쓰면. @@@@인터닝.
        
#### - 1. 데이터타입
    -Q) 숫자 몇 가지? int, float, complex(@@), bool,
    - 근데 int를 더 쪼개.
        - c에서 int 많이 배웠죠. long, unsigned int, longlong, 전부다 넌파이가 지원해줌. 
        - 근데 우리는 지원해주는것만 알고 이제부터는 무조건 가장 큰 지원범위인 'int 64', 'float64'만 다룰거야.
    - 쉬운 이유: 데이터 타입 지정만 하면 지가 알아서 해줌
    
    -Q) 문자열 몇 가지? 3가지(  , ,,)@@@@
        - 근데 얘는 리틀 앤디언 빅앤디언도 지원해줍니다. @@@@@
        - 우리가 전 수업에서 수집한거 '넌파이'로 변형해볼거고 아주 효율적으로 처리해볼거에요
    -Q) u가 붙은거?
        - 언사인드. 부호가 없는애. 
            - 파이썬 int 특징: 오버플로 없다. 무한정 크기 느릴 수 있다. 
    - 수 많은 객체를 변환할 수 있다. 
        - 아마 데이터 분석하는 회사 가면 주니어라고 해서 '전처리'만 시키는데 아주 많이 할거에요. 저런거
        - 뒤에 언더바 있네 데이터 타입에 (string_)
        
- 데이터 형태 지정하기 dtype=np.Type
- 데이터 형태 확인하기: object.dtype
- 데이터 형태 변환하기: astype(np.Type)

#### 파이썬 언더바★★★★★
- 1. 앞에 언더바 하나)관례상 프라이빗. 
    - 그러나 관례상이 아니었던 곳이 있었어 from * 쓰는 경우 임포트 된다/안된다?  안된다.
    - 앞에 한개 붙으면 '프라이빗'으로 쓰인다. from import * 하면 안됨
- 2. 앞에 두개 붙을때 __) OOP할때 dir 할때 안 나왔어. 
    - 맹글링.(dir했더니 안나옴)
- 3. 앞에 둘 뒤에 둘) 매직메소드/스페셜 메소드
- 4. _
    - 관례상 필요없는 변수 이름 일때
- 5. _
    - 언더바가 마지막을 가리킬떄
- 6. 
    - 언더바 한개 붙고 이름을 _(a)로 표현하는경우
    - 다국어 처리하는 경우
- 7. 
    - 이름 뒤에 언더바 붙은 경우
    - 파이썬 키워드하고 똑같을때 이름 충돌을 피하려고 사용

#### 텐서플로우 예시

In [76]:
from tensorflow.keras.datasets import mnist

ModuleNotFoundError: No module named 'tensorflow'

In [75]:
data=mnlist.load_data()
data #결과에 array 나오니까, 이건 무슨 형태? 넌파이!

NameError: name 'mnlist' is not defined

#### dtype 단축표현
- 쉽게 다양한 타입을 찍어서 만들 수 있어요
- 교안 22페이지 참고해주세요

In [79]:
import numpy as np
a=np.array([[1,2],[3,4]], dtype='i2')#단축표현 가능

In [80]:
a

array([[1, 2],
       [3, 4]], dtype=int16)

#### dtype 단축 표현 몇 개 있는지 궁금하죠?

In [81]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint32,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float64,
 'g': numpy.float64,
 13: numpy.float64,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,
 'c

In [82]:
len(np.sctypeDict) 

152

#몇 개인지 알고 싶으면 len. 넌파이가 32비트, 64비트인 사람따라 이 갯수 달라. 더 알고 싶으면 아래와 같이 해보세요

In [83]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/missr/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/missr/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/missr/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/U

In [84]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

#### 우리가 볼 데이터
- 컴플렉스 관심 X
- 불도 관심 X (integer랑 같으니까)
- 따라서 우리는 int 64, float 64, 128만 볼거에요

#### Strides
- 일련으로 저장된것을 약수로 나눠보면 그 구조를 거꾸로 알 수 있음
- (6,2)는 6/2=3. 즉 3개가 구조체 갖고 있는식. 
[0,1,2/
 3,4,5/
 6,7,8] 이런식인데 값4를 한번에  접근할 수 있음
- 벡터라이즈는 동시에 계산 <한번> 합니다.

- 뉴럴네트워크
    - 일차원 배열을 넣었을거야. 
        - 이차원배열로 구조를 만들면 더 복잡한데 굳이 필요없어
        - 스트라이드 개념있으니 차원은 쉽게 변환할 수 있으니까
        - 그래서 모든 뉴럴 네트워크 기반에서 플래튼 시키는데 그 이유가 스트라이드가 숨어있어서야

#### 
- 데이터 크기도 고려해야합니다.
- 64bit=8바이트, 32bit=4바이트

#### 엔리스트
- 한 행으로 플래팅 형태로 바꾸어도 상관ㅡ이 없어요
- 우리는 스트라이드를 알고 있기에. 



#### 예시_ Strides(12,4)
- [1,2,3/4,5,6/7,8,9]가 있다고 할때 (3행3열)
- 이건 현재 int32짜리라 한칸씩 넘어갈때 4바이트씩 필요함.
- 즉 row>row에는 12바이트, column>column은 4바이트 필요함 (재은이와 결론)

#### 스트라이드가 복잡해질 수 있어
- 넌파이는 2가지 저장 방식 지원
    - 씨방식(가로), 포트란 방식(세로)
    - 따라서 스트라이드가 씨/포트란 따라 달라
        - strides(12,4) C
        - strides(4,12) fortran 
- 특정값 찾을때 효율적임

### AXIS
- 행끼리 계산은 axis(0)
- 열끼리 계싼은 axis(1)
    - stride가 있음 찾기 쉽나? 네. 
- 속도가 빠른이유: strides 있어서
- 꼼수로 shape 10*3인 행렬에 대해서 
    - 액시스0은? 0자리의 10을 가린다. 그럼 몇개? 3개. 
    - 액시스 1은? 1자리의 3을 가린다. 그럼 몇개? 10개. 

### 교수님 정리
- 넌파이는 로우 레벨
- 넌파이를 모르면 전체 프레임워크를 이해 못해서 다 암기해야함. 그러면 결국 빨리 잊어버림
- 이제 조금 복잡한 예시할게요
    - 아까 펙토리 메소드

#### range는 어디부터 어디까지이고, 넌파이도 유사한거 있ㅇ므

In [89]:
a=np.arange(10)

In [90]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### reshape
- 모양 변경

In [91]:
a.reshape(2,5) #2행 5열로 변경 #뮤터블이면 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 뮤터블이면 ..해@@야하는데, a는 안 바뀜
뮤터블 함수의 결과는 3가지
- 1. 자기자신은 안 바뀌는데 리턴은 넌
- 2. 리턴은 있지만 안바뀜
- 3. 리턴은 바뀌는데 ... 

#### 뮤터블에서는 추가해서 카피 갔죠
- 스왈로 카피, 디카피

#### 넌파이는 더 나아갔어
- 카피 개념이라서 reshape는 재할당 해야해요

In [92]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a=a.reshape(2,5)

In [94]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 나 열만큼 합을 구하고 싶어
- sum을 해볼까
- a.sum 하고 SHIFTTAB해보니 axis 나와. 
- 얘 2,5라서 결과가 5개 나오겠지 @
- 액시스 영이면 영가린댔죠. 그럼 결과 5개 나와요. 그럼 

In [96]:
a.shape

(2, 5)

In [97]:
a.sum(axis=1) # 행

array([10, 35])

In [100]:
a.sum() #전체 합

45

In [99]:
 a.sum(axis=0) #열

array([ 5,  7,  9, 11, 13])

#### 평균도 구하고 싶어

In [101]:
a.mean()

4.5

In [103]:
a.shape

(2, 5)

In [102]:
a.mean(axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [105]:
a.mean(axis=1)

array([2., 7.])

### axis 안에 strides 개념이 숨어있어서 행열별로 빠르게 연산이 가능합니다.
- 그럼 정말 속도 빠른지 궁금해
- 아래 예시를 봐. sum보다 이게 16배 더 빨라

In [110]:
%time sum(range(10000000)) #@@@time부분 복습

Wall time: 413 ms


49999995000000

In [111]:
%time np.sum(np.arange(10000000))

Wall time: 32.9 ms


-2014260032

### 보통 프로그래밍은 미리 구현하고 최적화하나, 넌파이는 최적화가 이미 되어있으니 구현하면 자동적으로 최적화가 됨

### 세번째. matlab
- 얘는 말만 할게요
- 데이터의 기본 구조가 메트릭스, R은 벡터. 
- 넌파이도 벡터. 그러나 메트릭스를 지원해주기도 함(우리는 안 쓴대)
- 매트릭스는 2차원 고정이라 유연하지 못해서 교수님은 별로 안 좋아하심.
- 매트립 쓰는 사람들은 습관이래:0
- 공식 홈페이지에 있으니 쓸 사람들은 찾아서 쓰세요.
- 15년 전에는 파이썬, R 도 없어서 메틀랩만 있었고, 그때 500만원 주고 사야했대. 그리고 연간 250주고 연회원가입했대

#### 이제부터 어려운거 끝이래.(믿을 수 없음^-^)

### 이제 데이터 한번 만들어 볼게요
1. np.array, 팩토리 메소드 방식
- 클래스 방식으로 만드는 법에서 에러가나오기도 함. 그래서 쉽게 만드는게 np.array, 팩토리 메소드 방식

2. 

#### 3행 4열짜리 만들어보아요.
- shape은 아까봤듯 튜플 형태!@@@@@@@@@@@@**************

In [116]:
a=np.zeros((3,4)) #shift-tab(shape)

In [117]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 1로도 만들어-ones

In [119]:
b=np.ones((3,3))

In [120]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 6으로 만들고 싶어0 full
- shift tab(ST)
- 

In [124]:
c=np.full((3,2),6)

In [125]:
c

array([[6, 6],
       [6, 6],
       [6, 6]])

#### 그럼 약간 이상한게 있어.
- 아까 제로스 치면 zeros_like 나왔고, ones_like도 나왔어.

### like
- 내가 지정한 애랑 동일항 행/열로 만들어줘요
- 행렬 연산할때 크기가 중요해요. shape이 똑같아야해.
- 이거 사용하면 크기 맞춰서 뭘 해준대
- 대신 값은 1로 다 채워주고

In [127]:
d=np.ones_like(a) #a하고 똑같은데, 1로 다 만들어준다. 형태 똑같아.

In [128]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 단위행렬
- eye, identity
- ST쳐보니 shape 없어.
- 단위행렬은 정방 행렬만 단위행렬이죠.

### eye

In [129]:
b=np.eye(3)

In [130]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### identity
- 단위행렬 eye와 identity는 어떤 차이가 있니
- ST qhk.
- eye는 많은 옵션있고 아이덴티티는 옵션 적고 빨리
- 즉 둘다 단위행렬 만들 수 있어

In [132]:
c=np.identity(3)

In [133]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 대각행렬
- diag

In [135]:
b=np.dia

AttributeError: module 'numpy' has no attribute 'dia'

## 산삼각행렬

In [139]:
b=np.tri(3)

In [140]:
b

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

## 하 삼각행렬(?)

In [141]:
b=np.tril((3,3))

In [142]:
b

array([[3, 0],
       [3, 3]])

## 전체 행렬
- triu
- transpose

In [143]:
np.triu((3,3))

array([[3, 3],
       [0, 3]])

In [144]:
np.transpose(b)

array([[3, 3],
       [0, 3]])

## 직교행렬
- 오솔로

## linespace()
- 라인별로 자를 수 있어

In [145]:
d=np.linspace(0,100) # 0~100Rkwl 50등분

In [146]:
d

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

## logspace()

In [149]:
e=np.logspace(1,100)

In [150]:
e

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [151]:
### 이름 있는 행렬들 다 만들 수 있다
- 유 다이아 엘
- 유

SyntaxError: invalid syntax (<ipython-input-151-69c5db2ac82c>, line 2)

## empty
- C에서 선언하면 쓰레기 들어가는것과 동일
- 쉽게 만드는거 다양하게 지원

In [152]:
e=np.empty((4,2))

In [153]:
e

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 6.32404027e-321],
       [6.95314361e-310, 6.95314361e-310]])

# 만들었으면 이제 특정한거 뽑아낼거야

In [155]:
a=np.arange(10).reshape(2,5)

In [156]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 특정한거 뽑아내는 개념 2가지
### 1. 인덱싱/슬라이스
 - 지원하는: 시퀀스 타입.
 - 시퀀스 중요한건 : 순서
 - 넌파이는 순서 할까? 중요해요. 그럼 인덱싱 될까? 인덱싱 되어요. 
 
### 2. 키(인덱스 에러랑 유사한거 키에러.)

## 넌파이 인덱싱
- 8을 뽑아내기 위해서는? 위의 a 어레이
- 파이썬) a[1][-2], a[1][3]
- 넌파이) a[1,3] 
    - 이건 파이썬에서 지원해주는게 아니야. 내가 원하는거 빠르게 지원해줌. 컴마 지원
    
#### a[:,3] 
- 콤마 앞이 행, 콤마 뒤가 열. 그러니까 모든 열에서 4번쨰 지원

In [159]:
a[1,3] #8뽑기

8

In [158]:
a[:,3]

array([3, 8])

#### 3차원

In [161]:
a=np.arange(27).reshape(3,3,3)

In [162]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### 여기서 가운데 녀석들만 뽑고 싶다면? 9~17까지의 수

In [163]:
a[1] #방법1

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [165]:
a[1,:] #방법2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [167]:
a[1,:,:] #@@@@@@@@@@@

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

#### 넌파이에서 떙떙떙 ...
- 전부다를 가져와줘
- 파이썬도 사실 있엉

In [168]:
a[1,...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

#### 1,4,7,10,13,16,19,22,25만 뽑아보세요
- 교안 38페이지 참고★
- 한줄 뽑아올 때 for 쓰면 돌려야하는데 넌파이는 빠르게 계산할 수 있어. 바로 뽑잖아
- 넌파이는 일주일 만에 할 수 있어요.:( 거짓말 조금 더 보탰어.

#### 뒤에 조건을 넣을 수 있어요

In [258]:
a=np.arange(10)

In [186]:
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [187]:
a[a>3 & a<8] #에러

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [188]:
 a[(a>3) & (a<8)] #이건 가능 and

array([4, 5, 6, 7])

In [189]:
 a[(a>3) | (a<8)] #d이건 OR

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 마스킹 기법
- 트루인 애만 뽑기

In [271]:
a=np.arange(10)

In [260]:
a[[True, False, True,True,True,True,True,True,True,True]] 

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [254]:
a

[[True, False, True, True, True, True, True, True, True, True]]

In [253]:
type(a)

list

In [191]:
a>3

TypeError: '>' not supported between instances of 'list' and 'int'

#### 팬시 인덱싱
-  마스킹과 유사. 꺽쇄가 두개. 
- a[[1,2]] 1행,2행 뽑아

### 넌파이 기반 판다스는 이거보다 더 추가된 인덱싱 지원합니다.
-

In [196]:
a=np.arange(10).reshape(5,2)

In [198]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### 팬시인덱싱 쓰면 행 딱 이쁘게 

In [197]:
a[[1,3]]

array([[2, 3],
       [6, 7]])

## 추가 5가지 넘파이 지원하는 것
- 콤마 땡떙떙 조건 마스크 팬시 인덱싱 //마조팬시...,
>> 마스크: 트루만 뽑기

### 콤마 앞은 행, 뒤는 열

마스크 1이 투르, 영은 폴스

## 괄호 두개!
- 팬시 인덱싱!
- 행만 뽑아요
- a[[1,2,4],[2,3,4]]는 (1,2),(2,3),(4,4)에 있는거 뽑는거

### 시퀀스 타입은 뭐 쓸 수 있따?
- 인덱싱, 슬라이싱
- 포 뒤에 쓸 수 있다.
    - 그러나 벡터라이즈한 기법이 아니기 때문에 넌파이 싸대기인거야. (파파팍. 절대로 쓰면 안 돼)

## 포 안쓰면======================================= 
- 포 쓰면 벡터라이즈에 어긋나~ 싸다구!

#### iter하면 느낌적인 느낌으로?
- next

In [201]:
b=np.nditer(a)

In [202]:
next(b)

array(0)

#### 함수도 잘 고려해서 만들어야해요

In [203]:
def add_(a,b):
    return a+b
#만약에 이런 함수는 벡터라이즈 함수일까?!

In [204]:
x=np.arange(5)
y=np.arange(5)

In [205]:
add_(x,y) #더하기니까 저런게 된느거야. 더하기 함수가 있으니까. 

array([0, 2, 4, 6, 8])

#### 곱하기 문제없어

In [206]:
x*3

array([ 0,  3,  6,  9, 12])

#### 더하기는?
- 숫자 +문자 == 노.
- 리스트 + 숫자 ==노

그러나

#### 브로드 캐스팅
- 간단한 크기는 넌파이가 알아서 맞춰줘요.
- 특정 열의 값에서 3더하고 싶으면, 그냥 더하기 3하면 됨
- 그러나 복잡한. 너무 모양이 다르면 자동화 할 수 없어서 브로드 캐스팅 노노
- 4.3 행렬과 1*3 행렬짜리도 더하기 가능해

In [209]:
3+np.arange(10)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### 브로드캐스팅은 복잡하면 크기 안 맞춰줌
- operands could not be broadcast together with shapes (2,) (10,)

In [211]:
np.array([1,2])+np.arange(10) #operands could not be broadcast together with shapes (2,) (10,)

ValueError: operands could not be broadcast together with shapes (2,) (10,) 

## ufunc
- u: universial 보편적인
    - 넌파이에서 원소 한개 짜리 스칼라에ㅐ서도 지원이 되고, 벡터에도 지원이 됨. 
    - 범용적으로 사용되는 함수
        - 예) 절대값.
- type에 ufunc 나오는 순간 여러개도 가능하고 한개만 넣어도 된다
    - np.ceil([2.9,1,2,3,0.3])해서 shiftTab 눌렀을때.

In [212]:
# 파이썬 절대값
abs(-1)

1

In [214]:
#이렇게 하면 에러나
abs([-1,1,2])

TypeError: bad operand type for abs(): 'list'

In [217]:
# 절대값
np.abs(-1)

1

#### 넌파이에서는 이런 경우에 대해서도 절대값으로 변환 되네
- 그러나 위에서 보듯이 일반 abs 함수로는 절대값 치환하면 타입 에러 발생

In [216]:
np.abs([-1,1,2])

array([1, 1, 2])

#### 넌파이에서 올림함수

In [218]:
np.ceil([2.9,1,2,3,0.3])

array([3., 1., 2., 3., 1.])

# 파이썬 넌파이 쉬운 이유 ========================
1. 인덱싱,슬라이싱
2. 브로드 캐스트
     - 지가 알아서 해줘서 안 어려움
3. ufunc
    - 우리가 다 사용할 수 있어요. 

====================================================================================

In [219]:
## 넌파이 자체에서 설명 보는 방법
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x00000202904B0B70>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

#### /짝대기는 포지셔널 온리, *별표는 키워드. 키워드 이후부터는 키워드만 써야함

In [221]:
np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

#### 팩토리얼은 재귀함수로
- 파이썬에서 재귀함수는 좋아요 안 좋아요? 별로 안 좋아요.
- 파이썬은 테일 안 지원해서 속도 느리다고 했어요. 
- 그 해결책으로 싸이파이에서 

#### 팩토리얼

In [222]:
from scipy.special import factorial

In [226]:
factorial(3)

array(6.)

In [228]:
factorial([3,4,5])

array([  6.,  24., 120.])

#### np.info(factorial)
싸이파이도 넌파이로 만들었음. 그래서 이것도 인포로 설명 읽을 수 있어요

In [230]:
np.info(factorial)

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


#### iinfo
- 인티저 타입에 대한 인포메이션 알려줌. 

In [232]:
np.iinfo(3)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

## np.where
- where은 조건절. 
- 아주 중요해요
- 용법1) 조건을 만족하는 '인덱스'!!!!!!@!!!!!!!!!

In [266]:
b=np.arange(10)

In [235]:
np.where(b>5) #이건 별 느낌 없음

(array([6, 7, 8, 9], dtype=int64),)

#### 조건에 맞으면 0으로, 아니면 1로 써라

In [236]:
np.where(b>5, 0,1)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

#### 조건을 만족하는 인덱스!

In [267]:
b=np.arange(5,10) 

In [268]:
b[np.where(b>5)] #얘는 값이 나오니까 6,7,8,9

array([6, 7, 8, 9])

In [269]:
b #해당되는 b는 값이 5,6,7,8,9

array([5, 6, 7, 8, 9])

In [270]:
np.where(b>5)#np.where는 인덱스를 가져오니까 해당되는 인덱스는 1,2,3,4에 대한 거(인덱스0인건 5라 충족X)

(array([1, 2, 3, 4], dtype=int64),)

#### np.max

In [273]:
np.max(b)

9

#### np.argmax(b) , np,argmin(b)
- 가장 큰거 '인덱스', 가장 작은거 인덱스

In [274]:
np.argmax(b)

4

In [275]:
np.argmin(b)

0

In [276]:
#### np.argmin()
- b.argmin() :클래스에서 함수로 사용하는 메소드 방식
    - 넌파이는 함수로 쓸때는 np.argmin, 메소드로 쓸때는 b.argmin()

0

#### 넌파이는 함수로 쓸때는 np.argmin, 메소드로 쓸때는 b.argmin()

- 둘다 지원하는게 대부분인데 간혹 안 지원하는 곳도 있음
- 얘네 차이는 shiftTab
- 파이썬은 펑셔나고 메소드 경계가 약했죠. 

In [277]:
b.argmin()

0

#### pi
- 파이썬에 있는 패키지하고 똑같아.
- 굳이 새로 만들 필요가 없는데 왜 math에 있는데 사용하는가
    - 임포트할때 (whose치면) 메쓰 한번 더 치면 메모리 올라가니까 효율 떨어져
    - 자주 쓰는애 있어요.
- pi is mpi 다른건) 메모리 위치가 달라서
- 그러나 우리는 파이 값만 같으면 되는거니까 상관없어요

In [281]:
from numpy import pi
from math import pi as mpi

In [282]:
pi

3.141592653589793

In [283]:
mpi

3.141592653589793

In [285]:
pi==mpi

True

In [286]:
pi is mpi

False

#### 땡떙떙
-1. 인덱스 슬라이싱에서 전부 표현
-2. 줄임표
- 그런데 이거 사용하지 마세요. 실수 많이 나니까

In [288]:
type(...)

ellipsis

In [287]:
dir(...)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [289]:
vars(...) #이건 안돼. 딕트가 없으니까 안되징

TypeError: vars() argument must have __dict__ attribute

https://docs.scipy.org/doc/numpy/user/quickstart.html

-아이템 사이즈는 바이트 사이즈로
-결과가 어레이이면 넌파이이다.
-dtype은 알수없는데 기본적으로 디타입만 쳐도 되어요
- 가장중요한건 shape, dtype  알면 싹 
- ndarray도 엔피점 어레이로 팩토리 메소드 방식으로 쓰면 좀 편하게 쓸 수 있다.

- linespace(0,2,9) 0에서2까지 9등분
- sine 그래프
- 새로 생성하는거 어레이, 제로, 제로라이크, 엠티, 라인스페이스 등 다 했는데 '랜덤' . 랜덤이 골치아픈데 판다스 끝나고 할거에요. 랜덤은 굉장히 중요한 애에요. 왜냐하면 우리가 만든 ㅇ라고리즘이 랜덤에서도 잘 돌아가야하니까요. 
- 프롬펑션, 프롬 파일 이건 파이썬하고 유사해. 느낌오지. 어떤 펑션 및 파일로부터 만드는데이건 판다스할떄 할거에요. 예습한다고 하면 뭐라고 하진 않을거에요. 
- 만들고 나서 출력은 전혀 문제가 아니고
- 떙떙떙. 잘봐야해. 우리 떙떙떙은 인덱싱 슬라이싱할떄 단축 표현이었잖아. 이거 하면 모든거 싹 다 쓸 떄 였어. 그런데 저 떙떙땡은 ;줄임표 에서도 사용됨. 
- 곱하기(A*B)는 엘리먼트와이즈, 
- 골뱅이(A@B)는 파이썬에서 검생이 안되는데 넌파이때문에 만든 연산자. 
- 이 연산자는 유일하게 넌파이만 사용 가능. 파이썬 3.6 이상
- 골뱅이는 행렬식 연산자. 
- A.dot(B)
    - dot은 내접. 실제로는 행렬곱
- 행렬곱 2가지 방식
- 랜덤은 잠시 넘어가고
- 유니버설 펑션) 보편적인거. 이동네에서 보편적인거 원소 한개. 벡털라이즈 안한거랑 한거 다 되는거
- np.exp(B)
    - 자연로그. 2.718하는. 
- np.sqrt: 제곱근 등
- 인덱싱과 슬라이싱 


- 카피
    - 파이썬에서는 승놜로 카피, 딥카피
    - 넘파이에서의 카피는 좀 달라

#### 아주 길때 몇개 볼지 고르는거
- np.set_printoptions(threshold=np.non)
- np.nan 되게 골치아파
    - 우리 이거 float 에서 본적 있죠
    - float과 무한대 형태로 있는데 np.nan. 아까 파이는 같았으나 이건 또 달라요. 이런건 외울수 밖에 없어★
- 하나 더 외워주세요
    - np.newaxis

In [290]:
np.nan

nan

In [291]:
float('nan')

nan

In [292]:
np.nan==float('nan')

False

In [293]:
t=float('nan')

In [294]:
np.set_printoptions(threshold=t)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [295]:
np.newaxis

In [296]:
np.newaxis==None

True

In [297]:
np.newaxis is None

True

#### 넌파이에서 카피

In [298]:
a=np.arange(10).reshape(2,5)

In [299]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [300]:
b=a

In [301]:
a[0][0]=100

In [302]:
#만야게 바뀌면 딥카피, 안 바뀌면 스왈로 카피

In [303]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [304]:
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [305]:
c=b.copy() #파이썬은 스왈로 카피였어요. 파이썬에서는 카피하면 스왈로 카피였어

In [306]:
b[0][0]=-100

In [307]:
b

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [308]:
a

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [309]:
c

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

# 파이썬은 카피copy()하면 스왈로인데, 넌파이는 딥카피야. 
- 넌파이는 다 중첩해
- 카피가 디카피야.
- 파이썬하고 반대야.

## 그럼 넌파이에서 스왈로 카피는?
- view

## 우리가 카피하는 이유
- 원본을 보호하기 위해서

In [310]:
c=b.view()

In [311]:
b[0][0]=2100


In [312]:
b

array([[2100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [313]:
c

array([[2100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [314]:
a

array([[2100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])