## 찾기

#### 관련된 메소드를 전부 다 찾아줌★★★
-  np.lookfor
- np.info

In [1]:
import numpy as np

In [6]:
np.lookfor('* array')

Search results for '* array'
----------------------------
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.modf
    Return the fractional and integral parts of an array, element-wise.
numpy.rint
    Round elements of the array to the nearest integer.
numpy.sqrt
    Return the non-negative square-root of an array, element-wise.
numpy.expm1
    Calculate ``exp(x) - 1`` for all elements in the array.
numpy.isnan
    Test element-wise for NaN and return result as a boolean array.
numpy.isnat
    Test element-wise for NaT (not a time) and return result as a boolean array.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, ele

#### 연습용 데이터 만들어볼게요
- 아래는 몇 차?

In [8]:
a=np.array(100) # 얘는 0차. 스칼라니까

#### 1차

In [9]:
a=np.array([1,2,3])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

#### 2차
- 2차부터는 액시스 개념이 있음
- 액시스 0은 로우, 액시스 1은 컬럼
- 여러개 있는 값을 하나로 줄일 수 있죠. 어제 sum 해봤으니
- 여러개를 하나로 줄이는거? 
    - 리덕션. 합 평균 쉽게 되는게 저 안에 스트라이드 개념이 숨어있기 때문.
- 넌파이에서 빠른 계산 가능한 이유?
    - 스트라이드가 숨어있어서

In [10]:
a=np.array([[1,2,3],[4,5,6]])

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

# 모양 바꾸기

## reshape
- strides 개념을 사용함
- 모양을 바꾸려면 갯수를 맞춰줘야함
- 주의) 뮤터플 펑션이 아니라서 자기 자신이 안 바뀜


### 값 주려면
- 재할당, 자기자신이 뮤테이션

In [13]:
a=np.arange(27)

In [14]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#### 얘는 1차. 콤마는 왜 표현을 했을까? 튜플로 표현했기에 하나짜리는 저렇게 표현한거에요. 

In [16]:
a.shape #얘는 1차. 콤마는 왜 표현을 했을까? 튜플로 표현했기에 하나짜리는 저렇게 표현한거에요. 

(27,)

In [20]:
b=a.reshape(3,9)

In [22]:
b[0][0]=100

In [23]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

#### reshape해서 재할당 했는데도 a가 변화했네. 
- 그래서 카피를 사용합니다!!
- 참조를 같이 하고 있기에 reshape하면 카피해야함
- 이 동네 카피는 뭐다? 기본적으로 딥카피.

#### reshape 쓰려면 아래처럼

In [25]:
b=a.reshape(3,9).copy()

In [26]:
b=a.reshape(3,-1) # -1이 9로 바뀜

In [27]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [28]:
b=a.reshape(-1,3)

In [29]:
b

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26]])

#### -1 2번 쓸 수는 없어

In [30]:
b=a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

#### -2, -100
- 마이너스 붙으면 지가 알아서 바꾸는데
- 관례상 마이너스 일 써
- 마이너

In [31]:
b=a.reshape(3,-100)

In [32]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

## Resize
- reshape는 재할당
- resize는 뮤터블이기에 자기 자신 변경
- 크기 안 맞추는 경우
    - 부족하면 자르고, 넘치면 0 패딩
- 네거티브 값 허용 안함

In [33]:
a.resize((3,9))

In [34]:
a

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [37]:
a=np.arange(27)

In [38]:
a.resize((3,5))

In [39]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 네거티브 허용 안함 

In [40]:
a.resize((-1,10))

ValueError: negative dimensions not allowed

# 배열 분할하기
- split : 기준점으로 쪼개고 리스트로 반환하는 타입
- split 3종류
    - split
    - vsplit: 텐서플로 트레이닝할때 사용
    - hsplit

In [42]:
a=np.arange(27)

In [44]:
a=a.reshape(3,9)

In [47]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

#### 펑션 방식/ 메소드 방식으로 접근
- 펑션이 없으면 메소드

#### split 자르는 기준 있어야함
- 1로 자르니까 되는데, 2로 하니 안돼

In [49]:
np.split(a,1)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [51]:
np.split(a,2)

ValueError: array split does not result in an equal division

#### split 튜플 형태로 자름
- 0~1까지, 1~2까지, 2~3까지

In [53]:
np.split(a,(1,2))# 0~1까지, 1~2까지, 2~3까지

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

#### 0~2까지, 2에서 2까지 자름

In [54]:
np.split(a,(2,2))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

#### 없는게 나올 수 있어 너무 크면

In [56]:
np.split(a,(2,5))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

#### 마이너스
- 얘는 영까지 잘리네
- 에러가 안 나는 대신 이 개념 잘 이해하고 있어야해 @@@
- 엑시스 개념 써야해. 

In [58]:
np.split(a,(-2,5)) # 이거 노노

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [60]:
np.split(a,(5,5),axis=1) 

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

#### 이거 불편해서 hsplit

In [61]:
np.hsplit(a,5) #안 되네. 어떤 개념? 튜플 사용

ValueError: array split does not result in an equal division

In [65]:
np.hsplit(a,(5,)) #??????????@@@@

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

### vsplit

In [66]:
np.vsplit(a,(2,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

#### split 액시스 0이 브이스플릿, 액시스1한게 브이스플릿

## stack

In [68]:
b=np.arange(5)

In [72]:
b

array([0, 1, 2, 3, 4])

In [69]:
c=np.arange(5,10)

In [73]:
c

array([5, 6, 7, 8, 9])

In [70]:
np.stack((b,c)) # 얘도 ST에서 액시스 개념있고, 기본이 액시스 영이야

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 액시스가 1이면

In [71]:
np.stack((b,c),1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### 스택 대신 에이치 스ㅐㄱ

In [74]:
np.hstack((b,c))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### stack 단축표현
- np.r_ 얘는 함수가 아니야.
    - 등장이유: 메트랩에 있어서

#### np.r_[[b,c]]

In [78]:
np.r_[b,c] 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### np.c_[[b,c]]

In [80]:
np.c_[[b,c]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### np.s_[b,c]

In [81]:
np.s_[b,c] #슬라이싱 객체 만들어 우리 안 할거

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

#### s언더바가 하는거

In [82]:
[1,2,3,4,5,][slice(1,5)]

[2, 3, 4, 5]

In [84]:
c=np.arange(5,10)

In [85]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
np.arange(10)[np.s_[1]]#@@@@@@@@@@@@@@@

1

#### 컬럼스택
- 붙일때 사용

In [88]:
np.column_stack([b,c])

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### 붙이는 라인 쪼개는 라인 기억하고 있어야해

### 차원변화
- 1차원>2차원
    - reshape

In [96]:
a=np.arange(6)

In [90]:
a #1차원

array([0, 1, 2, 3, 4, 5])

In [91]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [92]:
#### a=np.array([[0,1,2,3,4,5]])

In [93]:
a=np.array([[0,1,2,3,4,5]]) 이런 모양으로 만들고 싶으면?

In [97]:
a

array([0, 1, 2, 3, 4, 5])

In [98]:
a[np.newaxis] # [] 더 추가하고 싶어서 이거했어

array([[0, 1, 2, 3, 4, 5]])

In [99]:
np.newaxis is None

True

In [100]:
a[None] 

array([[0, 1, 2, 3, 4, 5]])

#### 이거 보기 싫죠? 그래서 np.newaxis 라는거 만들어서 새로운 축 만들었어
- np.newaxis
    > 새롭게 만드는거!!

#### 2차원

In [125]:
a=np.arange(6)

In [126]:
a=a.reshape(2,3)

In [127]:
a # 이렇게 하면 3차원으로 바뀌어요@@@

array([[0, 1, 2],
       [3, 4, 5]])

이렇게 하면 3차원으로 바뀌어요

#### 값 각각을 차원화 하고 싶다면?

In [128]:
a[:, np.newaxis]

array([[[0, 1, 2]],

       [[3, 4, 5]]])

#### ?!

In [109]:
a[:,:, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [110]:
a=np.arange(6)

In [111]:
a

array([0, 1, 2, 3, 4, 5])

#### 위에서 각각 []로 맞추려면?

In [112]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

#### 이거 어려워서 쓴느거?
- expand_dims()

In [113]:
np.expand_dims(a,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [114]:
np.expand_dims(a,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

#### 이거 3차원으로 증가 되나?
- 더이상 증가할 수 없다고 하고 2차원으로 증가해주네
- 즉 차원을 1개씩 밖에 못올려

In [115]:
np.expand_dims(a,2)

C:\Users\missr\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

#### 3차원으로 바꿨는데 이거 주의할점
- 2차원이 3개 붙었다고 생각할 것

In [118]:
a=np.arange(27).reshape(3,3,3)

In [119]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### 1차원<> 3차원 가능하나? 
- 이럴때 사용하는게
- swapaxes((,))***************** 축끼리 값 변경
- moveaxies((,))*****************축 이동

In [123]:
np.swapaxes(a,0,2)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [124]:
np.moveaxis(a,0,2)

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

#### 넌파이는 빠르고 쉬워서 쓴다했고 다른 프레임워크 기본
1. 만드는 방법
2. 인덱스 슬라이스 하는거
3. 브로드캐스트
4. ufunc
5. shape 관련된 부분 배웠어요
    - 연산하려고 하면 모양 다 맞춰줘야해서 힘드니 잘 알아둡시다:)

## Structured Arrays★★★★★
- https://docs.scipy.org/doc/numpy/user/basics.rec.html
- userGuide>Numpy Basics> Structured arrays
- 이거 기반으로 판다스를 만들어서 중요한 이슈에요
- 넌파이에서는 사용자 데이터를 어떻게 만들것인가. 
- 기본적으로 호모지니어스인데, 아니게 만들 수 있어( 근데 결과적으로는 호모지니어스야)
- 그 방식은 <사용자 데이터 타입>을 만드는 거에요
- 우리가 배울때 '문자형','숫자형',float'있으면 자동적으로 형변환되게 했었는데 dtype보니까 

#### 사용자 타입 만드는 방법
- 정형화된 데이터 타입을 만들고 싶을때 주로 이 방법을 사용합니다.
- 타입은 '튜플'형태로 만들어요. ★
    - 처음은 이름, 두번째는 타입
        - dtype[('name','U10'),('age','i4'), ...]
    - 이런 정보가 쌓이면 DB처럼 사용할 수 있어요.
- 사용자 데이터 타입은 리스트 형태이며 각각 요소가 '이름(문자열)', '나이(int)','무게'로 해서 할 수 있죠.
- 아래에서 실습을 똑같이 해볼게요

#### 장점
- 

In [156]:
x=np.array([('Rex', 9,81.0),('Fido',3,27.0)], dtype=[('name','U10'),('age','i4'),('weight','f4')]) #@@@@@@@@@@

In [157]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

### 네임드 튜플
- 위의 스트럭쳐드 어레이와 유사한 네임드튜플

In [133]:
from collections import namedtuple

In [134]:
namedtuple

<function collections.namedtuple(typename, field_names, *, rename=False, defaults=None, module=None)>

#### 파이썬에서 타입 네임은? 클래스 (Sift Tab해봐)

In [135]:
Address=namedtuple('Address',('name','age','weight'))

In [136]:
al=Address('Rex', 27,81.0)

#### 이 방식은 클래스 만드는 거하고 같네요
- 우변의 'Address' 이게 클래스 명

In [137]:
al.name

'Rex'

In [138]:
al

Address(name='Rex', age=27, weight=81.0)

In [140]:
b=(1,)

In [141]:
dir(b)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

#### 카운트하고 인덱스는 튜플에서 사용되네

### 파이썬 클래스 정의?
- 정의 안 해도 된다
- 메타클래스 쓰면 클래스 정의 안해도 클래스 처럼 쓸 수 있어
- 네임드 튜플도 유사해.
- 튜플에 있는 인덱스하고 카운트까지 지원해
- 따라서 얘는 튜플이라서 어떻게 쓸 수 있따?
    - al[0]
    - al[1] 
    - 즉, 이름 및 인덱스로도 사용할 수 있음


In [145]:
al[0]

'Rex'

In [146]:
al['name']

TypeError: tuple indices must be integers or slices, not str

#### 보통 인덱스로 접근하면, '키'로는 접근이 안돼. 생성은 되지만

#### 네임드 튜플에서 안 된거?
- 키로 네임 접근하니까 안되었음. ★
- 그러나 넌파이 스트럭쳐드는 키로도 접근이 가능함★
    - 이 방식은 편히 '딕셔너리'방식이라고 할게요. 그럼 어떤 데이터만 가져오냐면 
        - 즉, 행으로도, 열로도 가능해요
        - 인덱스 치면 로우 가져온다. 튜플/딕셔너리 방식으로하면 컬럼 데이터를 가져온다

In [148]:
x['name']

NameError: name 'x' is not defined

#### 엑셀은 디스크 기반. 가상 IO 기반
- 그러나 스트럭쳐드 어레이는 메모리에서 돌기에 속도 빨라
- 인덱스 치면 로우 가져온다. 튜플/딕셔너리 방식으로하면 컬럼 데이터를 가져온다

#### 앞서 정의한 x에서 name이 있는지 확인해볼게요
- 없죠. 
- 즉 이건 어트리뷰트 방식으로는 접근 못해요
- 그러나 네임드 튜플은 '키'방식으로 접근 못했지.
- 즉 데이터 타입마다 값을 추출하는 방식이 조금씩 달라요 

In [155]:
#ir(x) #name 나오니? 
'name' in dir(x)

False

#### 나만의 데이터 구조를 만들 수 있다

## Pandas
- 잠시 돌아갔다 올게요 

### 아까 숫자로 인덱스 시켰죠.
- 그러면 얘가 숫자인지 문자인지 모르겠죠. 넌파이에서는 name이 문자라서 얘로 뽑으면 세로로 했고, 인덱스로는 가로로 뽑앗는데
- 판다스에서는 이름도 숫자로 표현되어서 위와 같은 방식으로 ㄹ바로 쓸 수 없어
- 그래서 판다스가 어떤 고민을 했냐
    - 