# 기계학습
- 싸이킷 기반으로 코딩을 이용해서 할 것이다
- GUI 기반으로 하면 쉽지만 유연성이 떨어진다. 확장 모듈이 있지만 그것보다 싸이킷이 낫다.
- 융합 학문이다.
- The Elements of Statistical Learning : 굉장히 어려운 책이다. pdf로 무료본이 있다.
- 결과(예측)가 중요하다. 결과 높이는 것이 중요한 이슈.
- 설명이 가능하지 않으면 믿지 않는 경우도 있다. 
- Transfer learning 
- reingorcement learning(강화 학습) : 제조업이랑 연관시켜서 할 수 있다. 
- 딥러닝이 발전 속도가 매우 빨라서 기계학습의 일부임을 알지만 다른 분야로 부르는 사람들도 많아졌다.
- Data로부터 Specific 문제 해결을 위한 최적의 모델 만들기
    - 가장 중요한게 Data
    - 일반화된 모델, 알고리즘을 사용할 수 없다.
    - 최적:성능이 좋아야하고, unseen data에 대해서도 잘 분석하는 모델을 만들어야 한다.
    - 모델은 overfitting하면 안된다.
    - 성능 -> 결과 예측
    - 일반화된 모델을 일컫는 말. 마스터 알고리즘(책도 있음)

Pedro Domingos : 유명한 사람

- bias: 결과와 떨어진 정도
- variance(분산, 흩어진 정도): 결과들이 퍼져있는 정도 
- bias가 작을수록 variance 작을 수록 좋다.
    - 둘 다 작기는 쉽지 않다. trade-off 관계에 있으므로 하나가 커지면 하나가 작아지는 관계이다.
    - 적절한 모델을 찾는 것이 중요하다.

#### 모델이 복잡해지면
- bias가 작아진다.
- variance가 커진다.
- 둘을 합쳐서 가장 작아지는 모델을 찾아야한다. -> model selection

학습시킬수록 bias가 줄고 Training error가 작아지지만 variance가 높아져서 Test Error가 커진다.

## Sklearn
- 판다스 기반으로 할 것이다.
- 판다스가 여러가지랑 붙는 허브이다.

1. load_ : 크기가 작아서 바로 쓸 수 있는거
2. fetch_ : 크기가 커서 불러와서 쓸 수 있는거
3. make_ : 랜덤으로 데이터를 불러오는 거

In [10]:
from sklearn.datasets import load_iris # 스네이크 방식 -> 함수
import pandas as pd

C:\Anaconda\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Anaconda\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
data = load_iris()

넘파이 데이터 -> 넘파이 기반
- cpu지원이 안된다.

In [3]:
data # 넘파이 데이터 -> 넘파이 기반

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

Bunch -> 갈래상 묶음을 의미 : 데이터 묶음 -> 쪼갤 수 있다.

In [4]:
type(data)

sklearn.utils.Bunch

In [5]:
dir(data)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

항상 도메인 지식을 위해 설명이 있어야한다. -> .DESCR

In [9]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
iris = pd.DataFrame(data.data)

컬럼을 demension / feature라고 한다.

In [13]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
iris = pd.DataFrame(data.data, columns=data.feature_names)

결과값(라벨링 타겟) 값이 없다.

In [16]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9     

In [22]:
iris_target = pd.DataFrame(data.target, columns=['target'])

타겟 안에 들어가는 값들이 타겟 네임이다.

In [23]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [24]:
iris_target

target
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
..      ...
120       2
121       2
122       2
123       2
124       2
125       2
126       2
127       2
128       2
129       2
130       2
131       2
132       2
133       2
134       2
135       2
136       2
137       2
138       2
139       2
140       2
141       2
142       2
143       2
144       2
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

하나의 테이블로 합친다. -> concat
- axis=1 : 좌우로 붙인다.
- axis=0 : 위아래로 붙인다.

In [26]:
iris = pd.concat([iris,iris_target], axis=1)

In [27]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              

데이터 가져왔으니 여기서부터 시작이다.

1. 알고리즘 불러온다.

In [28]:
from sklearn.neighbors import KNeighborsClassifier # irish data는 classification하는 데이터

camel 방식 명명법 -> type이 class -> 인스턴스화 해야한다.

model selection 관점 -> 최적의 모델을 찾는다. -> 옵션을 바꿔서 최적의 모델을 찾는다

인공지능 책
- 인공지능 1: 현대적 접근방식 (픽터 노빅) -> 전 세계적인 책 
- Unreasonable Effectiveness of Data(2009) Peter Norvig

알고리즘별로 분석을 했는데 중요한 것은 좋은 데이터의 양이었다.
- 세상에 좋은 데이터가 별로 없으므로 알고리즘이 중요하다.
- 데이터가 많으면 많을 수록 좋다 -> 많으면 좋은 데이터일 가능성이 높다.

하이퍼 파라미터

2. 인스턴스화 한다.

In [30]:
knn = KNeighborsClassifier()

3. 학습 시킨다.(training) 적합시킨다.(fit)
    - training 데이터와 target 데이터를 분리해서 넣는다

갈래상 행렬은 대문자 벡터는 소문자 ...?

In [ ]:
iris[iris.columns[:-1]]
iris.iloc[:,:-1]

In [31]:
knn.fit(iris.iloc[:,:-1], iris[iris.columns[-1]])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

학습 전 후의 vars 비교 
- 학습시켜서 새로운 객체를 만들었다는 것을 확인

In [32]:
knn2 = KNeighborsClassifier()

In [33]:
vars(knn2)

{'n_neighbors': 5,
 'radius': None,
 'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'p': 2,
 'n_jobs': None,
 'weights': 'uniform'}

In [34]:
vars(knn)

{'n_neighbors': 5,
 'radius': None,
 'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'p': 2,
 'n_jobs': None,
 'weights': 'uniform',
 'outputs_2d_': False,
 'classes_': array([0, 1, 2]),
 '_y': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'effective_metric_params_': {},
 'effective_metric_': 'euclidean',
 '_fit_method': 'kd_tree',
 '_fit_X': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
    

학습을 시킴 -> 예측할 수 있다.

In [37]:
knn.predict([[3,3,3,3]])

array([1])

In [38]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

괄호 한 개 -> 에러 x,1형태로 넣어라
- 무조건 2차원 데이터를 넣어야 한다. 

In [39]:
knn.predict([3,3,3,3])

ValueError: Expected 2D array, got 1D array instead:
array=[3 3 3 3].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [41]:
knn.predict([[3,4,1,2],[3,3,3,3]])

array([0, 1])

In [46]:
knn.predict([[3,4,1,2]]) # -> setosa로 예측

array([0])

predict_proba : normalization 시킨다.
- 결정 평면이 1개인 것은 proba가 없을 수 있다.

In [48]:
knn.predict_proba([[3,3,3,2]])

array([[0. , 0.8, 0.2]])

In [49]:
knn.predict([[3,3,3,2]])

array([1])

차원에 대한 설명

In [42]:
import numpy as np

In [45]:
a = np.array([1,2,3,4]) # -> 1차원 방향이 없다.
a = np.array([1,2,3,4]).reshape(1,4) # -> 2차원으로 바꿔줌

In [44]:
a

array([[1, 2, 3, 4]])

모델 selection 관점 이므로 모델을 바꿔서 해보자

In [51]:
knn2 = KNeighborsClassifier(n_neighbors=3)

In [54]:
knn2.fit(iris.iloc[:,:-1], iris[iris.columns[-1]])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [55]:
knn2.predict([[3,3,3,2]])

array([1])

In [56]:
knn2.predict_proba([[3,3,3,2]])

array([[0., 1., 0.]])

get_params : 내가 바꿀 수 있는 하이퍼 파라미터들 -> 바꿔서 성능을 바꿀 수 있다.
- 주의 : 성능의 종류가 여러가지이다.
- 정확도 높일 때도 사용되고 속도도 포함된다. cs 관점으로 본 것.
- n_jobs(number of ~): 몇개의 코어를 사용해서 학습시킬 건지 -> 동시에 여러개 코어를 했으니 속도가 빠르다 -> 예측할 때 빨리 하는 것도 성능이다.

In [59]:
knn2.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 3,
 'p': 2,
 'weights': 'uniform'}

In [ ]:
knn2 = KNeighborsClassifier(n_neighbors=3, n_jobs=-1) # n_jobs=-1은 자동 : 최고로 많이 사용해서 계산 