In [1]:
import time

In [2]:
time.time()

1563863628.7538898

In [3]:
import datetime

In [4]:
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'sys',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

In [ ]:
datetime.datetime ## 귀차너!

In [17]:
from datetime import datetime, timedelta

In [10]:
datetime

datetime.datetime

In [11]:
a = datetime(2019, 7, 22) # 객체로 보관

In [13]:
dir(a)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'astimezone',
 'combine',
 'ctime',
 'date',
 'day',
 'dst',
 'fold',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'now',
 'replace',
 'resolution',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'today',
 'toordinal',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'weekday',
 'year']

In [14]:
a.year

2019

In [16]:
a.today()

datetime.datetime(2019, 7, 23, 15, 39, 6, 594589)

In [18]:
b = timedelta(99)

In [19]:
a+b

datetime.datetime(2019, 10, 29, 0, 0)

In [21]:
import numpy as np

In [31]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [32]:
a.dtype = 'int8'

In [33]:
a

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0], dtype=int8)

In [34]:
a.astype('float64')

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0.])